# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-05 23:15
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0002_auto_20180627_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='support_email',
            field=djstripe.fields.StripeCharField(help_text='A publicly shareable support email address for the business', max_length=255, null=True),
        ),
    ]
